# PostgreSQL Configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${POSTGRES_USER:myuser}
quarkus.datasource.password=${POSTGRES_PASSWORD:mypassword}
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:mydb}

## Hibernate ORM
# Управление схемой (раскомментируйте для автоматического обновления БД при разработке)
# quarkus.hibernate-orm.database.generation=update

# Логирование SQL
quarkus.hibernate-orm.log.sql=true
#quarkus.hibernate-orm.log.bind-parameters=true
quarkus.hibernate-orm.log.format-sql=true

# Connection Pool
quarkus.datasource.jdbc.max-size=20
quarkus.datasource.jdbc.min-size=2

# OpenAPI
quarkus.smallrye-openapi.path=/openapi
quarkus.smallrye-openapi.info-title=Jira API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=Jira like task management API

# Logging
quarkus.log.level=INFO
#quarkus.log.category."com.vsu.odinaev".level=DEBUG

# Детальное логирование Hibernate (опционально, для отладки)
#quarkus.log.category."org.hibernate.SQL".level=DEBUG
#quarkus.log.category."org.hibernate.type.descriptor.sql.BasicBinder".level=TRACE

# Application
quarkus.http.port=8080