# PostgreSQL Configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${POSTGRES_USER:myuser}
quarkus.datasource.password=${POSTGRES_PASSWORD:mypassword}
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:mydb}

## Hibernate ORM

# Connection Pool
quarkus.datasource.jdbc.max-size=20
quarkus.datasource.jdbc.min-size=2

# OpenAPI
quarkus.smallrye-openapi.path=/openapi
quarkus.smallrye-openapi.info-title=Jira API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=Jira like task management API

# Logging
quarkus.log.level=INFO

# Application
quarkus.http.port=8080

# JWT
mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.issuer=jira-api

#Basic
#quarkus.http.auth.basic=true
#quarkus.security.jdbc.enabled=true
#quarkus.security.jdbc.principal-query.sql=SELECT password_hash FROM users WHERE username=?
#quarkus.security.jdbc.principal-query.password-mapper.algorithm=bcrypt

# HTTP Security Policy
quarkus.http.auth.permission.permit-auth.paths=/v1/auth/register,/v1/auth/token
quarkus.http.auth.permission.permit-auth.policy=permit
quarkus.http.auth.permission.authenticated.paths=/v1/tasks,/v1/tasks/*,/v1/projects,/v1/projects/*,/v1/board,/v1/board/*
quarkus.http.auth.permission.authenticated.policy=authenticated

# Dev: автосоздание схемы + seed data
%dev.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%dev.quarkus.hibernate-orm.sql-load-script=import.sql
%dev.quarkus.hibernate-orm.log.sql=true
%dev.quarkus.hibernate-orm.log.format-sql=true

# Swagger UI
quarkus.swagger-ui.always-include=true